# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnlineEventApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnlineEventApp
  pod 'StreamChat', '~> 2.2'
  pod 'VoxeetUXKit', '~> 1.3'
end
